# Generated by Django 5.2.8 on 2025-11-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Serial_Number', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=30)),
                ('Brand_Name', models.CharField(max_length=50)),
                ('Product_Code', models.IntegerField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
